import os
import urllib.request
import json
import datetime
from fyers_apiv3 import fyersModel

CLIENT_ID = "77QN6WHNT3-100"
ACCESS_TOKEN = os.environ.get("FYERS_ACCESS_TOKEN")

if not ACCESS_TOKEN:
    print("Error: FYERS_ACCESS_TOKEN environment variable not set.")
    exit(1)

fyers = fyersModel.FyersModel(client_id=CLIENT_ID, token=ACCESS_TOKEN)

# 1. Fetch VIX from Yahoo to align IV
start_epoch = 1704067200
end_epoch = int(datetime.datetime.now().timestamp())
headers = {'User-Agent': 'Mozilla/5.0'}

def fetch_vix():
    url = f"https://query1.finance.yahoo.com/v8/finance/chart/^INDIAVIX?period1={start_epoch}&period2={end_epoch}&interval=1d"
    req = urllib.request.Request(url, headers=headers)
    try:
        print("Downloading India VIX data...")
        with urllib.request.urlopen(req) as res:
            data = json.loads(res.read())
            result = data['chart']['result'][0]
            timestamps = result['timestamp']
            closes = result['indicators']['quote'][0]['close']
            
            vix_map = {}
            for i, ts in enumerate(timestamps):
                date_str = datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d')
                if closes[i] is not None:
                    vix_map[date_str] = round(closes[i], 2)
            return vix_map
    except Exception as e:
        print(f"Error fetching VIX: {e}")
        return {}

vix_map = fetch_vix()

# 2. Fetch 15-Min Candles from Fyers (last 60 days)
range_from = (datetime.datetime.today() - datetime.timedelta(days=60)).strftime('%Y-%m-%d')
range_to = datetime.datetime.today().strftime('%Y-%m-%d')

def fetch_fyers_candles(symbol):
    data = {
        "symbol": symbol,
        "resolution": "15",
        "date_format": "1",
        "range_from": range_from,
        "range_to": range_to,
        "cont_flag": "1"
    }
    try:
        print(f"Fetching 15-min candles for {symbol} from {range_from} to {range_to}...")
        res = fyers.history(data=data)
        if res and res.get('s') == 'ok':
            return res.get('candles', [])
        else:
            print(f"Fyers Error for {symbol}: {res}")
            return []
    except Exception as e:
        print(f"Error calling history for {symbol}: {e}")
        return []

nifty_candles = fetch_fyers_candles("NSE:NIFTY50-INDEX")
bank_candles = fetch_fyers_candles("NSE:NIFTYBANK-INDEX")

# 3. Format candles for JS
def format_candles(candles, symbol_name):
    records = []
    # Sort candles by timestamp
    sorted_candles = sorted(candles, key=lambda x: x[0])
    
    last_valid_vix = 14.0
    
    for c in sorted_candles:
        ts, open_p, high_p, low_p, close_p, vol = c
        dt = datetime.datetime.fromtimestamp(ts)
        date_str = dt.strftime('%Y-%m-%d')
        
        # Calculate tick index (9:15 AM is 0, each candle is 15-min)
        hour = dt.hour
        minute = dt.minute
        tickIdx = (hour * 60 + minute - (9 * 60 + 15)) // 15
        
        if 0 <= tickIdx <= 24:
            v_val = vix_map.get(date_str, last_valid_vix)
            if date_str in vix_map:
                last_valid_vix = vix_map[date_str]
                
            iv = v_val if symbol_name == 'NIFTY' else v_val * 1.25
            
            records.append({
                "date": date_str,
                "tickIdx": tickIdx,
                "spot": float(close_p), # We use close of 15m candle as the price point
                "open": float(open_p),
                "high": float(high_p),
                "low": float(low_p),
                "close": float(close_p),
                "iv": round(iv, 2),
                "r": 0.07
            })
    return records

nifty_records = format_candles(nifty_candles, 'NIFTY')
bank_records = format_candles(bank_candles, 'BANKNIFTY')

# 4. Write to JS File
js_content = f"""/**
 * Real Intraday 15-Minute Market Data for Nifty 50 and Bank Nifty (Recent ~60 Days)
 * Auto-generated by fetch_real_intraday.py using Fyers API and India VIX.
 */
const RealIntradayData = {{
    NIFTY: {json.dumps(nifty_records, indent=2)},
    BANKNIFTY: {json.dumps(bank_records, indent=2)}
}};

// Export for ES Modules or Browser global
if (typeof module !== 'undefined' && module.exports) {{
    module.exports = RealIntradayData;
}} else {{
    window.RealIntradayData = RealIntradayData;
}}
"""

with open("real-intraday-data.js", "w") as f:
    f.write(js_content)

print("Successfully generated real-intraday-data.js!")
print(f"Nifty Intraday records: {len(nifty_records)}")
print(f"Bank Nifty Intraday records: {len(bank_records)}")
