import urllib.request
import json
import datetime

# Tickers
# Nifty 50: ^NSEI
# Bank Nifty: ^NSEBANK
# India VIX: ^INDIAVIX
# Date range: Jan 1, 2024 (1704067200) to June 16, 2026 (1781654400)
start_epoch = 1704067200
end_epoch = int(datetime.datetime.now().timestamp())

headers = {'User-Agent': 'Mozilla/5.0'}

def fetch_ticker_data(ticker):
    url = f"https://query1.finance.yahoo.com/v8/finance/chart/{ticker}?period1={start_epoch}&period2={end_epoch}&interval=1d"
    req = urllib.request.Request(url, headers=headers)
    try:
        print(f"Downloading historical data for {ticker}...")
        with urllib.request.urlopen(req) as res:
            data = json.loads(res.read())
            return data['chart']['result'][0]
    except Exception as e:
        print(f"Error fetching {ticker}: {e}")
        return None

# Fetch data
nifty_raw = fetch_ticker_data("^NSEI")
banknifty_raw = fetch_ticker_data("^NSEBANK")
vix_raw = fetch_ticker_data("^INDIAVIX")

if not nifty_raw or not banknifty_raw or not vix_raw:
    print("Error: One or more data feeds failed to download.")
    exit(1)

# Extract Nifty 50 quotes
nifty_ts = nifty_raw['timestamp']
nifty_quotes = nifty_raw['indicators']['quote'][0]
nifty_close = nifty_quotes['close']
nifty_open = nifty_quotes['open']
nifty_high = nifty_quotes['high']
nifty_low = nifty_quotes['low']

# Extract Bank Nifty quotes
bank_ts = banknifty_raw['timestamp']
bank_quotes = banknifty_raw['indicators']['quote'][0]
bank_close = bank_quotes['close']
bank_open = bank_quotes['open']
bank_high = bank_quotes['high']
bank_low = bank_quotes['low']

# Extract VIX quotes
vix_ts = vix_raw['timestamp']
vix_close = vix_raw['indicators']['quote'][0]['close']

# Convert timestamp to YYYY-MM-DD
def ts_to_date(ts):
    # Returns YYYY-MM-DD in local time
    return datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d')

# Map data
nifty_map = {}
for i, ts in enumerate(nifty_ts):
    date_str = ts_to_date(ts)
    if (nifty_open[i] is not None and nifty_high[i] is not None and 
        nifty_low[i] is not None and nifty_close[i] is not None):
        nifty_map[date_str] = {
            "open": round(nifty_open[i], 2),
            "high": round(nifty_high[i], 2),
            "low": round(nifty_low[i], 2),
            "close": round(nifty_close[i], 2)
        }

bank_map = {}
for i, ts in enumerate(bank_ts):
    date_str = ts_to_date(ts)
    if (bank_open[i] is not None and bank_high[i] is not None and 
        bank_low[i] is not None and bank_close[i] is not None):
        bank_map[date_str] = {
            "open": round(bank_open[i], 2),
            "high": round(bank_high[i], 2),
            "low": round(bank_low[i], 2),
            "close": round(bank_close[i], 2)
        }

vix_map = {}
for i, ts in enumerate(vix_ts):
    date_str = ts_to_date(ts)
    if vix_close[i] is not None:
        vix_map[date_str] = round(vix_close[i], 2)

# Align dates
all_dates = sorted(list(set(nifty_map.keys()) | set(bank_map.keys())))

nifty_records = []
bank_records = []

last_valid_nifty = None
last_valid_bank = None
last_valid_vix = 14.0 # Typical default IV if VIX data is missing for a specific date

for d_str in all_dates:
    # 1. Align Nifty
    n_val = nifty_map.get(d_str)
    if n_val:
        last_valid_nifty = n_val
    elif last_valid_nifty:
        n_val = last_valid_nifty
    else:
        continue # Skip dates before we have valid Nifty prices
        
    # 2. Align VIX (Implied Volatility)
    v_val = vix_map.get(d_str)
    if v_val:
        last_valid_vix = v_val
    else:
        v_val = last_valid_vix
        
    nifty_records.append({
        "date": d_str,
        "open": n_val["open"],
        "high": n_val["high"],
        "low": n_val["low"],
        "close": n_val["close"],
        "iv": v_val,
        "riskFreeRate": 0.07
    })

    # 3. Align Bank Nifty
    b_val = bank_map.get(d_str)
    if b_val:
        last_valid_bank = b_val
    elif last_valid_bank:
        b_val = last_valid_bank
    else:
        b_val = {"open": 48000.0, "high": 48000.0, "low": 48000.0, "close": 48000.0}
        
    # Bank Nifty options IV is typically higher than Nifty/VIX by ~25%
    bank_records.append({
        "date": d_str,
        "open": b_val["open"],
        "high": b_val["high"],
        "low": b_val["low"],
        "close": b_val["close"],
        "iv": round(v_val * 1.25, 2),
        "riskFreeRate": 0.07
    })

# Format and write JS file
js_content = f"""/**
 * Real Historical Market Data for Nifty 50 and Bank Nifty (2024 - 2026)
 * Auto-generated by fetch_real_data.py using Yahoo Finance API and India VIX.
 */
const RealHistoricalData = {{
    NIFTY: {json.dumps(nifty_records, indent=2)},
    BANKNIFTY: {json.dumps(bank_records, indent=2)}
}};

// Export for ES Modules or Browser global
if (typeof module !== 'undefined' && module.exports) {{
    module.exports = RealHistoricalData;
}} else {{
    window.RealHistoricalData = RealHistoricalData;
}}
"""

output_file = "real-data.js"
with open(output_file, "w") as f:
    f.write(js_content)

print(f"Successfully generated {output_file}!")
print(f"Nifty records: {len(nifty_records)}")
print(f"Bank Nifty records: {len(bank_records)}")
